# Generated by Django 2.0.7 on 2018-10-01 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='id',
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default='Value_Missing', max_length=2000, verbose_name='The description & learning outcomes of the module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='The modules unique code'),
        ),
        migrations.AlterField(
            model_name='module',
            name='ects',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], verbose_name='The ECTS provided on completion of the module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='lecturer',
            field=models.CharField(max_length=50, verbose_name='The name of the modules lecturer'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, verbose_name='The modules full name'),
        ),
    ]
