# Generated by Django 2.1.2 on 2018-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20181001_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='lecturer',
            field=models.CharField(max_length=50, verbose_name='The name of the module lecturer'),
        ),
    ]
