# Generated by Django 2.1.2 on 2018-10-12 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_auto_20181012_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_comment',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
