# Generated by Django 2.1.3 on 2018-11-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_module_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='lecturer',
            field=models.CharField(max_length=50, verbose_name='The modules lecturer'),
        ),
    ]
