# Generated by Django 2.1.2 on 2018-10-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_module_rating'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.ManyToManyField(to='modules.Module_Comment'),
        ),
    ]
