# Generated by Django 2.1.2 on 2018-10-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='The Lecturers full name with no professional title')),
                ('school', models.CharField(max_length=100, verbose_name='The school the lecture works in')),
            ],
        ),
    ]
